### ISSUE TITLE
yarn error in building account-cli

### ISSUE THREAD

**Issue by kFuQ** [RetricSu/gw-gitcoin-instruction#2]
Yarn does not work with account-cli build instructions listed at https://github.com/Kuzirashi/gw-gitcoin-instruction/blob/master/src/component-tutorials/3.setup.and.use.account.cli.md

I have gotten this error on 2 different machines running Ubuntu 20.04

yarn
**00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.**

 lsb_release -ar
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

 yarn --version
0.32+git

Please advise, as I would like to continue this project.

**Comment by e00dan** [comment]
You're using wrong `yarn`. Please see: https://github.com/yarnpkg/yarn/issues/2821#issuecomment-284181365.

**Comment by kFuQ** [comment]
Thank you for the advice.   I will try this.

**Comment by kFuQ** [comment]
Hi Daniel.

I installed yarn per suggestions and that worked.   However nodejs in ubuntu 20 is apparently 2 full major versions behind and i had to remove the stock nodejs and install nodejs 12.x per https://computingforgeeks.com/how-to-install-nodejs-on-ubuntu-debian-linux-mint/ and then ran npm update, then i was able to get the godwoken tools to finally build.

I believe that there should be a blurb in the instructions to install the newer versions of yarn and nodejs before building the tools.

Thanks for your help

**Comment by kFuQ** [comment]
please disregard the blurb/notes comment.  apparently i didn't see the requirements page 🙄🙄

have a great day
